import { CategorySlugType } from "types";

export const categoryDefaultNames: { [key in CategorySlugType]: string } = {
  "todos-productos": "Todos los productos",
  "desayuno": "Desayuno",
  "aderezos": "Aderezos",
  "aceites-y-grasas": "Aceites y grasas",
  "conservas": "Conservas",
  "endulzantes": "Endulzantes",
  "harinas-y-coladas": "Harinas y coladas",
  "galletas": "Galletas",
  "confiteria": "Confitería",
  "pastas-y-fideos": "Pastas y fideos",
  "snacks": "Snacks",
  "bebidas-alcoholicas": "Bebidas alcohólicas",
  "bebidas": "Bebidas",
  "carnicos": "Cárnicos",
  "hogar": "Hogar",
  "congelados": "Congelados",
  "frutas-y-verduras": "Verduras",
  "granos": "Granos",
  "huevos-y-lacteos": "Huevos y lacteos",
  "panaderia-y-pasteleria": "Panadería y pastelería",
  "mascotas": "Mascotas",
  "higiene-y-cuidado-personal": "Higiene y cuidado personal",
  "producto-nuevo": "Producto nuevo",
  "liquidacion": "Liquidación",
  "productos-online": "Productos online",
};