import { PAGE_Q_PARAM_NAME, PAGE_SIZE_Q_PARAM_NAME, PRICE_MAX_Q_PARAM_NAME, PRICE_MIN_Q_PARAM_NAME, SEARCH_QUERY_Q_PARAM_NAME, SUBCATEGORY_PARAM_NAME } from "@constants";

export type CATEGORY_PAGE_QUERIES = {
  [PAGE_Q_PARAM_NAME]: number;
  [PAGE_SIZE_Q_PARAM_NAME]: number;
  [PRICE_MIN_Q_PARAM_NAME]?: number;
  [PRICE_MAX_Q_PARAM_NAME]?: number;
  [SUBCATEGORY_PARAM_NAME]?: number[];
  [SEARCH_QUERY_Q_PARAM_NAME]?: string
}